[package]
name = "ruststreamer"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http="*"
gstreamer = "0.16"
gstreamer-video = "0.16"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.5.11"
tokio = "1.38.0"

serde_json = "1.0"
